### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by patricktoy** [theblixguy/DroidID#1]
When filling the password field at the login screen, macOS insists the password is incorrect, however it works when I type it out manually. When I try changing the stored password through the DroidID macOS app, the dialog gives no feedback when saving and continues to fail to log me in correctly.

Phone: Google Pixel w/ Android 7.1.1
Laptop: Macbook Pro w/ macOS Sierra 10.12.2

**Comment by theblixguy** [comment]
> When filling the password field at the login screen, macOS insists the password is incorrect, however it works when I type it out manually

Not sure why this happens, it works fine on mine (running macOS 10.12.4 16E144f) though. Have you checked whether the password length is the same as your original password and that you've entered the password correctly?

> When I try changing the stored password through the DroidID macOS app, the dialog gives no feedback when saving and continues to fail to log me in correctly

I've fixed it now. You should: 
1) Grab the latest copy of the app from suyashsrijan.com/droidid
2) Quit DroidID if it's running
3) Remove all existing copies of the app (including the ZIP files)
4) Move the new copy to the Applications folder
4) Run the app

**Comment by patricktoy** [comment]
Thanks for the fast fix for the change password dialog! I can verify that the dialog now closes when clicking save. Additionally, after waking the mac from sleep this morning, the login process via DroidId worked flawlessly. I'm not sure what the hiccup was yesterday. Thanks for the great app and support :)
